runtime: nodej20

handlers:
  - url: /(.*\.(js|css|ico|png|jpg|svg|json|txt|html))$
    static_files: build/\1
    upload: dist/.*\/(js|css|ico|png|jpg|svg|json|txt|html)

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html